databases:
  - name: mysitedb
    plan: free
    databaseName: mysite
    user: mysite

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: afterdb
          property: postgresql://dave:k7SJHR0suf5mPANcY601EMKduAuecTLv@dpg-cu4s8dl6l47c73ddvieg-a/afterglow_idif
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4